### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by INSANEANDSAD** [Iron-Miner/SeismicMod#2]
![Screenshot_20210509_123137_com android chrome](https://user-images.githubusercontent.com/81450153/117556996-dcd4a700-b0c2-11eb-8ac4-a1dae7afbe10.jpg)
![Screenshot_20210509_122625_com android chrome](https://user-images.githubusercontent.com/81450153/117557001-e100c480-b0c2-11eb-8010-e4e31aff3bc3.jpg)
hrm

**Comment by Iron-Miner** [comment]
no

**Comment by Iron-Miner** [comment]
but i am considering a resprite
